#version 460 core
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer LightPosBuffer { vec4 lightPos[]; };
layout(std430, binding = 1) buffer LightPosViewBuffer { vec4 lightPosView[]; };

layout(std140, binding = 0) uniform Matrices {
	mat4 projection;
	mat4 view;
};

uniform int lightCount;

void main() {
	uint i = gl_GlobalInvocationID.x;
	if(i >= lightCount) return;
	lightPosView[i] = view * lightPos[i];
}