#version 460 core

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, rgba8) uniform image2D inputImage;
layout(binding = 1, rgba8) uniform image2D outputImage;

void main() {
	ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(inputImage);

	if(uv.x < size.x && uv.y < size.y) {
		vec3 color = imageLoad(inputImage, uv).rgb;
		color.y = 1 - color.y;
		imageStore(outputImage, uv, vec4(color, 1));
	}
}